# Task 2:
    1. Load data.csv data file using pandas.
    2. Print out some sample rows and inspect the data sample to identify the dependent variables and independent variables.
    3. Examine the values of each attribute and select a set of attributes only that would affect to predict dependent variable.
    4. Split data between dependent (Y) and independent variables (X).
    5. Determine the data type (Discrete, Continuous, Categorical) of each attribute. 
       & Encode the dependent variable (as it is a string datatype) using a proper encoding scheme.


In [26]:
import pandas as pd
import numpy as np
import warnings 
np.set_printoptions(precision=20,suppress= False, formatter={'float_kind':'{:f}'.format})
warnings.filterwarnings('ignore')
df = pd.read_csv("data.csv")
df.columns

Index(['id', 'diagnosis', 'radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst', 'Unnamed: 32'],
      dtype='object')

In [27]:
df.head(6)

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   
5    843786         M        12.45         15.70           82.57      477.1   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   
5          0.12780           0.17000          0.1578              0.08089   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   
5  ...          23.75           103.40       741.6            0.1791   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   
5             0.5249           0.5355                0.1741          0.3985   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  
5                  0.12440          NaN  

[6 rows x 33 columns]

In [28]:
df.drop(['id', 'Unnamed: 32'], axis='columns', inplace=True)
df.columns

Index(['diagnosis', 'radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst'],
      dtype='object')

In [29]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
X, y = df.iloc[:, 1:].values, df.iloc[:, 0].values
target_encoder = LabelEncoder()

# Part 2: Scaling, Modeling and Hyper-parameter tuning.

    6. Split the data into train and test data, with a ratio of 70% train and 30% test.
       Don't forget to set a random state to maintain experiment consistency.
    7. Demonstrate results before and after using Standard Scaler. 
    8. Also output classifier train and test accuracy scores and confusion matrix for each result.

In [30]:
y = target_encoder.fit_transform(y)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1) # TEST = 30% TRAINING= 70%
print(X_train.shape)

(398, 30)


In [31]:
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix
classifier = SVC()
classifier.fit(X_train,y_train)# fitting data using SVC()
y_predict = classifier.predict(X_test)
classifier.score(X_test,y_test)# #accuracy of svc() model

0.9181286549707602

In [32]:
print(confusion_matrix(y_predict,y_test))

[[106  12]
 [  2  51]]


In [34]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_predict ))

              precision    recall  f1-score   support

           0       0.90      0.98      0.94       108
           1       0.96      0.81      0.88        63

    accuracy                           0.92       171
   macro avg       0.93      0.90      0.91       171
weighted avg       0.92      0.92      0.92       171



# Should you fit any preprocessing algorithms on the whole dataset? Why?

    yes, we should use normalization methods such as StandardScarer or MinMax and the like , so that each values of numeric columns in the dataset will use a common scale, without distorting differences in the ranges of values or losing information.

In [35]:
from sklearn.model_selection import GridSearchCV
from sklearn.preprocessing import StandardScaler
X, y = df.iloc[:, 1:].values, df.iloc[:, 0].values
scaler=StandardScaler()
X = scaler.fit_transform(X)
target_encoder = LabelEncoder()
y = target_encoder.fit_transform(y)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

In [36]:
classifier = SVC()
classifier.fit(X_train,y_train)
y_predict = classifier.predict(X_test)
classifier.score(X_test,y_test)

0.9736842105263158

In [37]:
print(confusion_matrix(y_predict,y_test))

[[71  2]
 [ 1 40]]


    9. Finally perform Hyper-parameter tuning using GridSearchCV or RandomSearchCV, 
      and note down the result train and test accuracies as well as the best parameters.

In [38]:
X, y = df.iloc[:, 1:].values, df.iloc[:, 0].values
scaler=StandardScaler()
X = scaler.fit_transform(X)
target_encoder = LabelEncoder()
y = target_encoder.fit_transform(y)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)
param_grid = {'C': [0.1, 1, 10, 100, 1000], 
              'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
              'kernel': ['rbf']} 
  
grid = GridSearchCV(SVC(), param_grid, refit = True, verbose = 3)
grid.fit(X_train, y_train)
grid_predictions = grid.predict(X_test)



Fitting 5 folds for each of 25 candidates, totalling 125 fits
[CV] C=0.1, gamma=1, kernel=rbf ......................................
[CV] .......... C=0.1, gamma=1, kernel=rbf, score=0.626, total=   0.0s
[CV] C=0.1, gamma=1, kernel=rbf ......................................
[CV] .......... C=0.1, gamma=1, kernel=rbf, score=0.626, total=   0.0s
[CV] C=0.1, gamma=1, kernel=rbf ......................................
[CV] .......... C=0.1, gamma=1, kernel=rbf, score=0.626, total=   0.0s
[CV] C=0.1, gamma=1, kernel=rbf ......................................


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    0.0s remaining:    0.0s


[CV] .......... C=0.1, gamma=1, kernel=rbf, score=0.626, total=   0.0s
[CV] C=0.1, gamma=1, kernel=rbf ......................................
[CV] .......... C=0.1, gamma=1, kernel=rbf, score=0.626, total=   0.0s
[CV] C=0.1, gamma=0.1, kernel=rbf ....................................
[CV] ........ C=0.1, gamma=0.1, kernel=rbf, score=0.967, total=   0.0s
[CV] C=0.1, gamma=0.1, kernel=rbf ....................................
[CV] ........ C=0.1, gamma=0.1, kernel=rbf, score=0.890, total=   0.0s
[CV] C=0.1, gamma=0.1, kernel=rbf ....................................
[CV] ........ C=0.1, gamma=0.1, kernel=rbf, score=0.956, total=   0.0s
[CV] C=0.1, gamma=0.1, kernel=rbf ....................................
[CV] ........ C=0.1, gamma=0.1, kernel=rbf, score=0.923, total=   0.0s
[CV] C=0.1, gamma=0.1, kernel=rbf ....................................
[CV] ........ C=0.1, gamma=0.1, kernel=rbf, score=0.945, total=   0.0s
[CV] C=0.1, gamma=0.01, kernel=rbf ...................................
[CV] .

[Parallel(n_jobs=1)]: Done 125 out of 125 | elapsed:    3.8s finished


In [39]:
grid.score(X_test,y_test)

0.9649122807017544

In [40]:
print(confusion_matrix(grid_predictions,y_test))

[[71  3]
 [ 1 39]]


In [41]:
from sklearn.metrics import classification_report
print(classification_report(y_test, grid_predictions))

              precision    recall  f1-score   support

           0       0.96      0.99      0.97        72
           1       0.97      0.93      0.95        42

    accuracy                           0.96       114
   macro avg       0.97      0.96      0.96       114
weighted avg       0.97      0.96      0.96       114



## Write Observations on benefits/disadvantages of Standardization/Normalization.

Compared to normalization which uses the min and max values to rescale the values from 0 to 1 using Standardization which uses the z score to scale the value is less prone to be affected by outliers in the dataset.
As you can see from the above code by scaling the dataset and fitting themin the model improves the accuracy score by 5%.

# Reference:
https://www.analyticsvidhya.com/blog/2020/04/feature-scaling-machine-learning-normalization-standardization/
https://www.geeksforgeeks.org/svm-hyperparameter-tuning-using-gridsearchcv-ml/